/**:
  ros__parameters:
    T_C_CH:
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    invert_T_C_CH: false
    sensor_is_lidar: true
    width: 512
    height: 16
    fov_up: 15.0
    fov_down: -15.0
    smooth_thre_ratio: 0.05
