/**:
  ros__parameters:
    T_C_CH:
    - -1.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 1.8
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    invert_T_C_CH: true
    sensor_is_lidar: true
    width: 1024
    height: 64
    fov_up: 3.0
    fov_down: -25.0
    smooth_thre_ratio: 0.05
