<?xml version="1.0"?>
<package format="3">
  <name>voxfield</name>
  <version>0.0.0</version>
  <description>Voxfield: non-projective signed distance field for online planning and 3D reconstruction</description>

  <author email="helen.oleynikova@mavt.ethz.ch">Helen Oleynikova</author>
  <author email="marius.fehr@mavt.ethz.ch">Marius Fehr</author>
  <author email="yuepan@student.ethz.ch">Yue Pan</author>

  <maintainer email="helen.oleynikova@mavt.ethz.ch">Helen Oleynikova</maintainer>
  <maintainer email="marius.fehr@mavt.ethz.ch">Marius Fehr</maintainer>
  <maintainer email="yuepan@student.ethz.ch">Yue Pan</maintainer>

  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>eigen</depend>
  <depend>libgoogle-glog-dev</depend>
  <depend>libgflags-dev</depend>
  <depend>protobuf-dev</depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
